//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myre.Graphics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XboxResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XboxResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Myre.Graphics.XboxResources", typeof(XboxResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] AmbientLight {
            get {
                object obj = ResourceManager.GetObject("AmbientLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Bloom {
            get {
                object obj = ResourceManager.GetObject("Bloom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BlurSSAO {
            get {
                object obj = ResourceManager.GetObject("BlurSSAO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CalculateLuminance {
            get {
                object obj = ResourceManager.GetObject("CalculateLuminance", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ClearGBuffer {
            get {
                object obj = ResourceManager.GetObject("ClearGBuffer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CopyTexture {
            get {
                object obj = ResourceManager.GetObject("CopyTexture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DirectionalLight {
            get {
                object obj = ResourceManager.GetObject("DirectionalLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Downsample {
            get {
                object obj = ResourceManager.GetObject("Downsample", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EdgeBlur {
            get {
                object obj = ResourceManager.GetObject("EdgeBlur", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EdgeDetect {
            get {
                object obj = ResourceManager.GetObject("EdgeDetect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Gamma {
            get {
                object obj = ResourceManager.GetObject("Gamma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Gaussian {
            get {
                object obj = ResourceManager.GetObject("Gaussian", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MarkGeometry {
            get {
                object obj = ResourceManager.GetObject("MarkGeometry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Nothing {
            get {
                object obj = ResourceManager.GetObject("Nothing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ParticleSystem {
            get {
                object obj = ResourceManager.GetObject("ParticleSystem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PointLight {
            get {
                object obj = ResourceManager.GetObject("PointLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] randomnormals {
            get {
                object obj = ResourceManager.GetObject("randomnormals", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RestoreDepth {
            get {
                object obj = ResourceManager.GetObject("RestoreDepth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Skybox {
            get {
                object obj = ResourceManager.GetObject("Skybox", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SkyboxModel {
            get {
                object obj = ResourceManager.GetObject("SkyboxModel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sphere {
            get {
                object obj = ResourceManager.GetObject("sphere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SpotLight {
            get {
                object obj = ResourceManager.GetObject("SpotLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SSAO {
            get {
                object obj = ResourceManager.GetObject("SSAO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ToneMap {
            get {
                object obj = ResourceManager.GetObject("ToneMap", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
